"""Core data structures for the Agent-to-Agent Communication Layer.

Everything here is plain dataclasses + enums so the layer has zero third-party
dependencies and can be serialised to JSON for any future transport
(WebSocket, message broker, A2A protocol, ...).
"""

from __future__ import annotations

import uuid
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import Enum
from typing import Any

BROADCAST = "*"
"""Special receiver value meaning "all online agents except the sender"."""


def new_id(prefix: str) -> str:
    """Generate a short, prefixed, globally unique id (e.g. ``msg_1f3a...``)."""
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


def utc_now() -> str:
    """ISO-8601 UTC timestamp with millisecond precision."""
    return datetime.now(UTC).isoformat(timespec="milliseconds")


class MessageType(str, Enum):
    """Semantic type of a message. Extend freely; unknown types are still routed."""

    CHAT = "chat"  # free-form conversation
    QUESTION = "question"  # expects an ANSWER
    ANSWER = "answer"
    TASK_REQUEST = "task_request"  # delegate work, expects TASK_RESULT
    TASK_ACCEPTED = "task_accepted"
    TASK_RESULT = "task_result"
    TASK_REJECTED = "task_rejected"
    REVIEW_REQUEST = "review_request"
    REVIEW_RESULT = "review_result"
    BROADCAST = "broadcast"
    STATUS = "status"  # presence / heartbeat / progress
    ERROR = "error"  # generated by the layer or an agent
    ACK = "ack"


class MessageStatus(str, Enum):
    CREATED = "created"
    SENT = "sent"
    DELIVERED = "delivered"
    PROCESSED = "processed"
    REPLIED = "replied"
    FAILED = "failed"
    TIMEOUT = "timeout"


class AgentStatus(str, Enum):
    ONLINE = "online"
    BUSY = "busy"
    OFFLINE = "offline"
    ERROR = "error"


@dataclass(slots=True)
class Message:
    """Structured message exchanged between agents.

    ``sender`` / ``receiver`` are **agent ids** (not display names).
    ``receiver`` may be :data:`BROADCAST`.
    """

    sender: str
    receiver: str
    content: str
    message_type: MessageType = MessageType.CHAT
    message_id: str = field(default_factory=lambda: new_id("msg"))
    conversation_id: str = field(default_factory=lambda: new_id("conv"))
    task_id: str | None = None
    timestamp: str = field(default_factory=utc_now)
    reply_required: bool = False
    in_reply_to: str | None = None
    status: MessageStatus = MessageStatus.CREATED
    metadata: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------ helpers
    def reply(
        self,
        content: str,
        *,
        message_type: MessageType | None = None,
        reply_required: bool = False,
        metadata: dict[str, Any] | None = None,
    ) -> Message:
        """Build a reply that keeps conversation/task ids and links to this message."""
        if message_type is None:
            message_type = _default_reply_type(self.message_type)
        return Message(
            sender=self.receiver,
            receiver=self.sender,
            content=content,
            message_type=message_type,
            conversation_id=self.conversation_id,
            task_id=self.task_id,
            in_reply_to=self.message_id,
            reply_required=reply_required,
            metadata=metadata or {},
        )

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["message_type"] = self.message_type.value
        d["status"] = self.status.value
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Message:
        data = dict(data)
        data["message_type"] = MessageType(data.get("message_type", MessageType.CHAT))
        data["status"] = MessageStatus(data.get("status", MessageStatus.CREATED))
        return cls(**data)


def _default_reply_type(t: MessageType) -> MessageType:
    return {
        MessageType.QUESTION: MessageType.ANSWER,
        MessageType.TASK_REQUEST: MessageType.TASK_RESULT,
        MessageType.REVIEW_REQUEST: MessageType.REVIEW_RESULT,
    }.get(t, MessageType.CHAT)


@dataclass(slots=True)
class AgentInfo:
    """Public descriptor of an agent as stored in the registry."""

    id: str
    name: str
    role: str
    model: str = "none"
    capabilities: list[str] = field(default_factory=list)
    endpoint: str | None = None  # reserved for network transports (URL / queue name)
    status: AgentStatus = AgentStatus.OFFLINE
    registered_at: str = field(default_factory=utc_now)
    last_seen: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["status"] = self.status.value
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AgentInfo:
        data = dict(data)
        data["status"] = AgentStatus(data.get("status", AgentStatus.OFFLINE))
        return cls(**data)
